synchronize:
  paths:
  - source: src/site/content/en
    exclude:
    - "lighthouse-seo/*.*"

pretranslate:
  segments:
    ignore_patterns:
    - "{# wf_(?!featured_snippet).*#}"
    - "^(Note|Caution|Warning|Success|Key Point|Key Term|Objective|Dogfood): "
    - "{:.*}"
    - "{%.*%}"
  paths:
  - source: bjc-German/bjc-German-translation_test3
    include:
    - "accessible/*.*"
